services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: event-driven-notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  kafka:
    image: apache/kafka:4.2.1
    ports:
      - "9092:9092"

  notification-service:
    build: .
    depends_on:
      - postgres
      - kafka
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: event-driven-notification
      DB_USERNAME: postgres
      DB_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"