spring:

  application:
    name: event-driven-notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/event-driven-notification
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        retry.backoff.ms: 1000
      retries: 0

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[traceId=%X{traceId:-},spanId=%X{spanId:-},correlationId=%X{correlationId:-}] "